/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    sectors: Sector;
    'future-objectives': FutureObjective;
    media: Media;
    pages: Page;
    news: News;
    projects: Project;
    testimonials: Testimonial;
    'team-members': TeamMember;
    'service-inquiries': ServiceInquiry;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    'future-objectives': FutureObjectivesSelect<false> | FutureObjectivesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'service-inquiries': ServiceInquiriesSelect<false> | ServiceInquiriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'am';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Internal CMS admin users only. Not visible to public site visitors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Square image recommended. JPG or PNG, max 2MB.
   */
  avatar?: (number | null) | Media;
  name: string;
  role?: ('admin' | 'editor' | 'reviewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The 6 service groupings. DO NOT add a 7th — see governance rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Do not change after creation.
   */
  slug: string;
  description?: string | null;
  capabilities?:
    | {
        capability: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lucide icon name (e.g. "Radio", "Network", "Zap")
   */
  icon?: string | null;
  /**
   * Display order (1–6 only — exactly 6 services)
   */
  order: number;
  _status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Target sectors (prospective). NOT existing clients — display as "Sectors We Serve".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Display order (1–14)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * PLANNED objectives only. Always shown with "Objective / Planned" label. Never mixed with current services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "future-objectives".
 */
export interface FutureObjective {
  id: number;
  /**
   * Objective number (1–8) as listed in Company Profile, Page 10
   */
  number: number;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Company news, announcements and press releases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Short summary shown in cards (2–3 sentences max).
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  category?: ('announcement' | 'project-update' | 'company-news' | 'partnership') | null;
  publishedAt?: string | null;
  _status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Completed and ongoing projects. Never invent client names — use sector categories only unless explicitly provided.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * e.g. "Fiber Optic Network Deployment — Addis Ababa"
   */
  title: string;
  /**
   * Short description for the showcase card.
   */
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  serviceCategory:
    | 'telecom-infrastructure'
    | 'fiber-optic'
    | 'satellite-wireless'
    | 'network-infrastructure'
    | 'telecom-power'
    | 'maintenance';
  /**
   * e.g. "Addis Ababa, Ethiopia" or "Across Ethiopia"
   */
  location?: string | null;
  /**
   * Sector category only — do NOT use specific client names without authorization. e.g. "Government Ministry" or "Telecom Operator"
   */
  clientSector?: string | null;
  completedAt?: string | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Client and partner testimonials. Only publish verified, real statements. Never fabricate.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Verbatim quote from the client or partner.
   */
  quote: string;
  /**
   * Full name of the person giving the testimonial.
   */
  authorName: string;
  /**
   * e.g. "Project Manager" or "Head of IT"
   */
  authorRole?: string | null;
  /**
   * Organisation name — only if authorized to publish.
   */
  organisation?: string | null;
  /**
   * Sector category if organisation name cannot be published.
   */
  sector?: string | null;
  avatar?: (number | null) | Media;
  _status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * GIX Nexus professional staff profiles. Only publish verified, real staff members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * e.g. "Managing Director", "Fiber Optic Technician"
   */
  role: string;
  /**
   * e.g. "Cisco Certified Network Professional", "SATCOM specialist"
   */
  qualification?: string | null;
  /**
   * Short professional summary (2-3 sentences).
   */
  bio?: string | null;
  /**
   * Key technical skills / areas of expertise.
   */
  specializations?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  photo?: (number | null) | Media;
  /**
   * Display order — Managing Director should be 1.
   */
  order?: number | null;
  _status: 'published' | 'draft';
  updatedAt: string;
  createdAt: string;
}
/**
 * Inquiry form submissions from the Capabilities page. Review and respond here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-inquiries".
 */
export interface ServiceInquiry {
  id: number;
  contactName: string;
  jobTitle?: string | null;
  organisation: string;
  sector?: string | null;
  email: string;
  phone?: string | null;
  serviceType:
    | 'telecom-infrastructure'
    | 'fiber-optic'
    | 'satellite-wireless'
    | 'network-infrastructure'
    | 'telecom-power'
    | 'maintenance'
    | 'multiple'
    | 'general';
  /**
   * Where in Ethiopia is the project?
   */
  location?: string | null;
  timeline?: ('urgent' | '1-month' | '1-3-months' | '3-6-months' | 'planning') | null;
  message?: string | null;
  /**
   * Track the inquiry lifecycle here.
   */
  status?: ('new' | 'reviewing' | 'contacted' | 'proposal-sent' | 'converted' | 'closed') | null;
  /**
   * Internal notes — not visible to the submitter.
   */
  adminNotes?: string | null;
  submittedAt?: string | null;
  /**
   * Captured at submission for audit purposes.
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'future-objectives';
        value: number | FutureObjective;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'service-inquiries';
        value: number | ServiceInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  capabilities?:
    | T
    | {
        capability?: T;
        id?: T;
      };
  icon?: T;
  order?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "future-objectives_select".
 */
export interface FutureObjectivesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  category?: T;
  publishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  description?: T;
  serviceCategory?: T;
  location?: T;
  clientSector?: T;
  completedAt?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  organisation?: T;
  sector?: T;
  avatar?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  qualification?: T;
  bio?: T;
  specializations?:
    | T
    | {
        item?: T;
        id?: T;
      };
  photo?: T;
  order?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-inquiries_select".
 */
export interface ServiceInquiriesSelect<T extends boolean = true> {
  contactName?: T;
  jobTitle?: T;
  organisation?: T;
  sector?: T;
  email?: T;
  phone?: T;
  serviceType?: T;
  location?: T;
  timeline?: T;
  message?: T;
  status?: T;
  adminNotes?: T;
  submittedAt?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}