import type { ImportMap } from 'payload'

// This file maps Payload's internal component paths to their actual modules.
// It is normally auto-generated by `payload generate:importMap`.
// Since that command fails on Node 24 (ESM/CJS issue), this is a minimal
// manual version that covers the standard Payload admin UI.
// Re-generate when adding custom Payload components.

export const importMap: ImportMap = {}
